ta404:
  application:
    name: ta404
    version: 5.1.1.RELEASE
spring:
  profiles:
    active: mybatis,dev
  application:
    name: ${ta404.application.name}
  main:
    allow-bean-definition-overriding: true
  banner:
    location: banner.txt
  output:
    ansi:
      enabled: always
  session:
    store-type: redis
server:
  port: 8083
  servlet:
    session:
      timeout: 7200s
    context-path: /ta404
